config/routes.rb
Rails.application.routes.draw do
  devise_for :users do
    get 'logout' => "devise/sessions#destroy"
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", :as => :rails_health_check
  get "search", to: 'profiles#search'
  patch "swipe_left", to: "matches#swipe_left"
  patch "swipe_right", to: "matches#swipe_right"
  post "pop_up_message", to: "messages#pop_up_message"

  # Defines the root path route ("/")
  # root "profiles#index"
  root "profiles#index"

  resources :profiles, only: %i[index show new create edit update] do
    resources :offers, only: %i[new create show]
  end
  resources :offers, only: %i[edit update destroy]
  resources :matches, only: %i[index show create] do
    resources :messages, only: %i[create]
  end
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<%# footer %>
    <div class="footer">

      <%= link_to profile_path(current_user.profile) do %>
        <div class="option"><i class="fa-solid fa-user fa-lg"></i></div>
      <% end %>

    <%= link_to profiles_path do %>
        <div class="option logo">
            <%= image_tag("https://res.cloudinary.com/dbd4uen7z/image/upload/v1701871540/skill-swap/orange-logo.png", alt: "Logo", size: "50x55") %>
        </div>
      <% end %>

      <%= link_to new_profile_offer_path(current_user.profile) do %>
        <div class="option"><i class="fa-solid fa-plus fa-lg"></i></div>
      <% end %>
    </div>

app/views/shared/_header.html.erb
   <%# header %>

<% if params[:controller] == "matches" && params[:action] == "show" %>
  <% initiator_profile = Profile.find_by(id: @match.initiator_id) %>
  <% creator_profile = Profile.find_by(id: @match.creator_id) %>
  <% correspondent_profile = current_user.id == @match.initiator_id ? creator_profile : initiator_profile %>

  <div class="header_chat">
    <%= link_to matches_path do %>
      <div class="option"><i class="fa-sharp fa-solid fa-arrow-left"></i></div>
    <% end %>
    <h3 class="navbar-name" style="margin-bottom: 0"><%= correspondent_profile.first_name %></h3>

    <%= link_to profile_path(correspondent_profile) do %>
      <%= cl_image_tag(correspondent_profile.photo.key, class: "profile-pic-messages") %>
    <% end %>
  </div>

<% elsif params[:controller] == "matches" && params[:action] == "index" %>

  <div class="header">
      <%= link_to profiles_path do %>
        <div class="option"><i class="fa-sharp fa-solid fa-arrow-left"></i></div>
      <% end %>
     <h3>Your Matches</h3>
    <i class="fa-arrow-left gone"></i>
  </div>

  <% elsif params[:controller] == "profiles" && params[:action] == "search" %>

  <div class="header">
      <%= link_to profiles_path do %>
        <div class="option"><i class="fa-sharp fa-solid fa-arrow-left"></i></div>
      <% end %>
      <h3>Filter your Search</h3>
      <i class="fa-arrow-left gone"></i>
  </div>

  <% elsif params[:controller] == "offers" && params[:action] == "new" %>

    <div class="header">
      <%= link_to profiles_path do %>
        <div class="option"><i class="fa-sharp fa-solid fa-arrow-left"></i></div>
      <% end %>
      <h3>Create an offer</h3>
      <i class="fa-arrow-left gone"></i>
  </div>


  <% elsif params[:controller] == "profiles" && params[:action] == "show" && @profile.user.id == current_user.id %>
    <div class="header">
     <%= link_to destroy_user_session_path, data: {turbo_method: :delete} do %>
        <div class="option"><i class="fa-solid fa-arrow-right-from-bracket fa-flip-horizontal"></i></div>
      <% end %>

      <%= link_to matches_path do %>
      <div class="option"><i class="fa-solid fa-comments"></i></div>
      <% end %>
  </div>
-----------
<% else %>

  <div class="header">
    <%= link_to search_path do %>
      <div class="option"><i class="fa-solid fa-sliders fa-lg"></i></div>
    <% end %>

    <%= link_to matches_path do %>
      <div class="option"><i class="fa-solid fa-comments fa-lg"></i></div>
    <% end %>
  </div>

<% end %>

app/views/shared/_ios_pwa_links.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="<%= image_path 'icons/apple-icon-57x57.png' %>">
<link rel="apple-touch-icon" sizes="60x60" href="<%= image_path 'icons/apple-icon-60x60.png' %>">
<link rel="apple-touch-icon" sizes="72x72" href="<%= image_path 'icons/apple-icon-72x72.png' %>">
<link rel="apple-touch-icon" sizes="76x76" href="<%= image_path 'icons/apple-icon-76x76.png' %>">
<link rel="apple-touch-icon" sizes="114x114" href="<%= image_path 'icons/apple-icon-114x114.png' %>">
<link rel="apple-touch-icon" sizes="120x120" href="<%= image_path 'icons/apple-icon-120x120.png' %>">
<link rel="apple-touch-icon" sizes="144x144" href="<%= image_path 'icons/apple-icon-144x144.png' %>">
<link rel="apple-touch-icon" sizes="152x152" href="<%= image_path 'icons/apple-icon-152x152.png' %>">
<link rel="apple-touch-icon" sizes="180x180" href="<%= image_path 'icons/apple-icon-180x180.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= image_path 'icons/favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="96x96" href="<%= image_path 'icons/favicon-96x96.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= image_path 'icons/favicon-16x16.png' %>">