config/routes.rb
Rails.application.routes.draw do
  devise_for :users do
    get 'logout' => "devise/sessions#destroy"
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", :as => :rails_health_check
  get "search", to: 'profiles#search'
  patch "swipe_left", to: "matches#swipe_left"
  patch "swipe_right", to: "matches#swipe_right"
  post "pop_up_message", to: "messages#pop_up_message"

  # Defines the root path route ("/")
  # root "profiles#index"
  root "profiles#index"

  resources :profiles, only: %i[index show new create edit update] do
    resources :offers, only: %i[new create show]
  end
  resources :offers, only: %i[edit update destroy]
  resources :matches, only: %i[index show create] do
    resources :messages, only: %i[create]
  end
end

app/models/match.rb
class Match < ApplicationRecord
  belongs_to :initiator, class_name: "Profile"
  belongs_to :creator, class_name: "Profile", optional: true
  has_many :messages
  enum status: [ :pending, :rejected, :accepted ]
  validates :initiator_id, uniqueness: {scope: :creator_id }
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  def show
    @accepted_matches = Match.where(
      status: 'accepted'
    ).where(
      'creator_id = ? OR initiator_id = ?',
      current_user.profile.id,
      current_user.profile.id
    )

    @match = Match.find(params[:id])
    @message = Message.new
  end

  def index
    @accepted_matches = Match.where(
      status: 'accepted'
    ).where(
      'creator_id = ? OR initiator_id = ?',
      current_user.profile.id,
      current_user.profile.id
    )

    @latest_messages = {}
    @accepted_matches.each do |match|
      @latest_messages[match.id] = match.messages.order(created_at: :desc).first
    end


  end

  def create
    @form_type = params[:match][:form]
    @profile_id = params[:match][:profile]
    @form_type == "like" ? swipe_right(@profile_id) : swipe_left(@profile_id)
  end

  def swipe_left(profile_id)
    if user_has_swiped(profile_id).nil?
      Match.create(
        initiator_id: current_user.profile.id,
        creator_id: profile_id,
        status: 'rejected'
      )
    else
      @match.rejected!
      @match.save!
    end
  end

  def swipe_right(profile_id)
    user_has_swiped(profile_id).nil? ? handle_initial_swipe_right(profile_id) : handle_its_a_match
    @match.save!
    respond_to do |format|
      profile = Profile.find(profile_id)
      msg = { status: @match.status, profile: profile.first_name, match_id: @match.id }
      format.json { render json: msg }
    end
  end

  private

  def handle_initial_swipe_right(profile_id)
    @match = Match.new(
      initiator_id: current_user.profile.id,
      creator_id: profile_id,
      status: 'pending'
    )
  end

  def handle_its_a_match
    @match.accepted! unless @match.rejected?
  end

  def user_matches
    Match.where(initiator_id: @test_profile.user_id)
  end

  def user_has_swiped(profile_id)
    @match = Match.where(
      'initiator_id = ? AND creator_id = ?',
      profile_id, current_user.profile.id
    ).first
  end
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/views/matches/index.html.erb
<div class="matches-container">
  <br>
  <% @accepted_matches.each do |match| %>
  <% correspondent = match.initiator.user == current_user ? match.creator : match.initiator %>
    <div class="match-item">
      <!-- ... Rest of your existing HTML content -->
  <%= link_to match_path(match) do %>

      <div class="match-background"></div>
      <div class="profile-image">
        <%= cl_image_tag(correspondent.photo.key, class: "profile-pic") %>
      </div>
      <div class="profile-details">
        <div class="profile-name">

          <strong><%= correspondent.first_name %></strong>
        </div>
        <% latest_message = match.messages.order(created_at: :desc).first %>
        <% if latest_message.present? %>
          <div class="latest-message">
            <%= latest_message.content %>
          </div>
        <% else %>
          <div class="no-message">
            No messages yet.
          </div>
        <% end %>

        </div>
      </div>
    </div>
    <hr>
   <% end %>
  <% end %>
</div>

app/views/matches/show.html.erb
<%# <% current_profile = Profile.find_by(user_id: current_user.id) %> %>
<% if current_user.id == @match.initiator_id || current_user.id == @match.creator_id %>
    <% initiator_profile = Profile.find_by(id: @match.initiator_id) %>
    <% creator_profile = Profile.find_by(id: @match.creator_id) %>

    <% correspondent_profile = current_user.id == @match.initiator_id ? creator_profile : initiator_profile %>

      <div class="container_chatroom"
        data-controller="match-subscription"
        data-match-subscription-match-id-value="<%= @match.id %>"
        data-match-subscription-current-user-id-value="<%= current_user.id %>">
        <div class="messages" data-match-subscription-target="messages">
          <% @match.messages.each do |message| %>
            <div class="message-row d-flex <%= message.sender?(current_user) ? 'justify-content-end' : 'justify-content-start' %>">
              <div class="<%= message.sender?(current_user) ? 'sender-style' : 'receiver-style' %>">
                <%= render "messages/message", message: message %>
              </div>
            </div>
          <% end %>
        </div>

        <div class="message-form">
          <%= simple_form_for [@match, @message],
            html: { data: { action: "turbo:submit-end->match-subscription#resetForm" },
            class: "d-flex"} do |f|
            %>
            <%= f.input :content,
              label: false,
              placeholder: "write your message",
              wrapper_html: {class: "flex-grow-1 chatInput", width: "100%", padding: "6px 12px"}
            %>
            <%= f.submit "Send", class: "btn-send mb-3 padd" %>

          <% end %>
        </div>
    </div>
<% else %>
  <p>Access denied</p>
<% end %>