config/routes.rb
Rails.application.routes.draw do
  devise_for :users do
    get 'logout' => "devise/sessions#destroy"
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", :as => :rails_health_check
  get "search", to: 'profiles#search'
  patch "swipe_left", to: "matches#swipe_left"
  patch "swipe_right", to: "matches#swipe_right"
  post "pop_up_message", to: "messages#pop_up_message"

  # Defines the root path route ("/")
  # root "profiles#index"
  root "profiles#index"

  resources :profiles, only: %i[index show new create edit update] do
    resources :offers, only: %i[new create show]
  end
  resources :offers, only: %i[edit update destroy]
  resources :matches, only: %i[index show create] do
    resources :messages, only: %i[create]
  end
end

app/models/offer.rb
class Offer < ApplicationRecord
  belongs_to :profile
  validates :description, presence: true
  validates :category, presence: true, inclusion: { in: ["Painting", "Drawing", "Calligraphy", "Candle Making", "Carpentry", "Ceramics", "Coding", "Embroidery", "Fishing", "Knitting/Crocheting", "Macramé", "Music", "Origami", "3D Printing", "Photography", "Sewing", "Skateboarding", "Soap Making", "Tattooing"] }
  has_one_attached :photo
  validates :photo, presence: true
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  before_action :find_profile, only: [:new, :create, :show]

  def new
    @offer = Offer.new
  end

  def create
    @offer = Offer.new(offer_params)
    @offer.profile = @profile
    if @offer.save
      redirect_to profile_path(@profile)
    end
  end

  def show
    @offers = Offer.where(profile_id: @profile.id)
  end

  def edit
    @offer = Offer.find(params[:id])
    @profile = @offer.profile
  end

  def update
    @offer = Offer.find(params[:id])
    @offer.update(offer_params)
    redirect_to profile_path(@offer.profile)
  end

  def destroy
    @offer = Offer.find(params[:id])
    @profile = @offer.profile
    @offer.destroy
    redirect_to profile_path(@profile), notice: 'Offer was successfully deleted.'
  end

  private
    def offer_params
      params.require(:offer).permit(:description, :category, :photo)
      #should I add picture here?
    end

    def find_profile
      @profile = Profile.find(params[:profile_id])
    end
end

app/helpers/offers_helper.rb
module OffersHelper
end

app/views/offers/_form.html.erb
<%= simple_form_for [profile, offer] do |f| %>
  <%= f.input :description, label: 'Description', error: 'description is mandatory, please specify one' %>
  <%= f.input :category, label: 'Category', hint: 'No special characters.', error: 'category is mandatory, please specify one' %>
  <%# should I specify the category at my models? %>
  <br>
<%= f.input :photo, as: :file, error: 'Photo is mandatory, please specify one' %>
<br>
  <%= f.button :submit, class: 'btn-flat', value: "Post Offer"  %>
<% end %>

app/views/offers/_show.html.erb
<% if @offers.nil? %>
<p> You dont have any offers</p>
<% else %>
  <% @offers.each do |offer|  %>
<div class="skill-card" style="background-image: linear-gradient(
    180deg,
    rgba(0, 0, 0, 0.4) 8.85%,
    rgba(255, 255, 255, 0) 47.4%,
    rgba(0, 0, 0, 0.4) 88.02%
    ), url('<%= cl_image_path(offer.photo.key) %>');">
  <div class="skill-description">
    <div class="text-wrapper"><%= offer.category %></div>
    <p class="p"> <%= offer.description %>
    </p>
  </div>
</div>
  <%= link_to "Edit", edit_offer_path(offer.id), class:"btn btn-secondary btn-lg"%>
  <%= link_to "Delete", offer_path(offer), class:"btn btn-secondary btn-lg", data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}%>
<% end %>
<% end %>
<% end %>

app/views/offers/edit.html.erb
<%= simple_form_for(@offer) do |f| %>
  <%= f.input :description, label: 'Description', error: 'Username is mandatory, please specify one', { class: 'large-input' } %>
  <%= f.input :category, label: 'Category', hint: 'No special characters.' %>
  <%# should I specify the category at my models? %>
  <%= f.input :photo, as: :file %>
  <%= f.button :submit, class: "btn btn-primary"   %>
<% end %>

app/views/offers/new.html.erb
<div class="form_container offer-form px-3">
<br>
  <%= render "form", offer: @offer, profile: @profile %>
</div>